spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: estudantes
          uri: lb://entudante-service
          predicates:
            - Path=/estudante-service/**


logging:
  level:
    org.springframework.cloud.gateway: debug