spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: estudante-service
          uri: lb://estudante-service
          predicates:
            - Path=/students/**
          filters:
            - RewritePath=/students/(?<segment>.*), /students/$\{segment}
        - id: sala-service
          uri: lb://sala-service
          predicates:
            - Path=/salas/**
          filters:
            - RewritePath=/salas/(?<segment>.*), /salas/$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: debug